name: Deploy Nomad Job

on:
  push:
    paths:
      - 'nomad-job/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Nomad CLI
      run: |
        curl -fsSL https://releases.hashicorp.com/nomad/1.5.7/nomad_1.5.7_linux_amd64.zip -o nomad.zip
        unzip nomad.zip
        sudo mv nomad /usr/local/bin/
        nomad version

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.BASTION_SSH_KEY }}

    - name: Create SSH tunnel to Nomad server via Bastion
      run: |
        nohup ssh -o StrictHostKeyChecking=no -N -L 4646:${{ secrets.NOMAD_PRIVATE_IP }}:4646 ec2-user@${{ secrets.BASTION_PUBLIC_IP }} &
        sleep 5
      shell: bash

    - name: Deploy Nomad Job
      env:
        NOMAD_ADDR: http://localhost:4646
      run: |
        nomad job validate jobs/your-job.nomad
        nomad job run jobs/your-job.nomad

    - name: Kill SSH tunnel
      run: |
        pkill -f "ssh -N -L 4646:${{ secrets.NOMAD_PRIVATE_IP }}:4646"
